### ISSUE TITLE
Tooltip content disappears on smartphone

### ISSUE THREAD

**Issue by pm5** [dmtintner/scss-tooltips#1]
The triangle showed up but the tooltip content is gone on smartphone layout.

Here's a screenshot of your [codepen example](http://codepen.io/dmtintner/full/GrcEK/) with the NE tooltip triggered, viewed in Firefox mobile view (the same goes for all other 3 directions):
![screen shot 2015-01-08 at 11 04 11](https://cloud.githubusercontent.com/assets/119645/5657228/318c0abc-9726-11e4-8595-d90356d35aa5.png)

**Comment by pm5** [comment]
Is no tooltips on smartphone a feature?  Seems like that according to the following line:

https://github.com/dmtintner/scss-tooltips/blob/master/tooltips.scss#L91

**Comment by dmtintner** [comment]
Yea, the thinking here was to remove the tooltips on smartphone because depending on the markup of the site, they can cause overflow issues. Plus, in most use cases I've had the tooltips were unecessary in that responsive view. The triangle still showing up in FF is a bug though. Will update the code to fix that. Also will update the readme to make this more clear

**Comment by pm5** [comment]
Just let you know I've sent a PR about that bug.  There might be better ways to fix it than using `!important`, though.  https://github.com/dmtintner/scss-tooltips/pull/2
